### PR TITLE
Update iOS application for Swift 3

### PR DESCRIPTION
**Pull request by glennrfisher**
This pull request updates the Cognitive Concierge iOS application for Swift 3 and uses the latest release of the Watson Developer Cloud iOS SDK (v0.9.1).

I ran the application in the simulator and think everything worked okay. It would be good to get another pair of eyes on it, though, just to make sure.

There are a few remaining warnings in Xcode. I think the "Plain Style unsupported in a Navigation Item" warnings is from the bar button items. Not sure if you saw that warning with earlier versions of Xcode and Swift.

image

### CODE REVIEW

**Comment by Ramshandilya** [comment]
Can we have the PR updated for Xcode 8.2, just in case.

**Review by Ramshandilya — APPROVED** [review]

**Comment by glennrfisher** [comment]
@Ramshandilya Just tried opening my PR in Xcode 8.2 and it looks like everything works okay. I did push a couple of new commits, though, just to bump the version numbers.

**Comment by Ramshandilya** [comment]
Hi @glennrfisher, It doesn't seem to build for me. Anything I'm missing.
> .../MessagesViewController.swift:19:8: Module compiled with Swift 3.0 cannot be imported in Swift 3.0.2: 
>/.../ConversationV1.framework/Modules/ConversationV1.swiftmodule/arm64.swiftmodule

**Comment by glennrfisher** [comment]
@Ramshandilya Can you try pulling the latest changes (i.e. the two commits I pushed earlier today), then running `carthage update --platform iOS` to download v0.10.0 of the Watson iOS SDK? Hopefully that will work for you.

**Comment by Ramshandilya** [comment]
Wondering if Xcode 8.2 was the culprit. 
screen shot 2016-12-21 at 11 20 12 am
Let me check after the update.

**Comment by bvennam** [comment]
Just tested this and merging in now.

**Pull request merged**
